 Suppose an online shopping company has collected customer purchase data from different stores before using the data for customer analytics and ml, the data scientist noticed several problems:

- duplicate customer records
- missing product prices
- incorrect data entries

need to:
- calculate business insight
- identify laptop customers

In [15]:
import numpy as np, pandas as pd
df=pd.read_csv("skills1a.csv")
df

   customer id customer     product    price    city
0          101    rahul      laptop  55000.0    pune
1          102    james      mobile  25000.0    pune
2          103     john      laptop  60000.0    pune
3          104    priya  headphones      NaN  mumbai
4          105      ken      laptop  55000.0    pune
5          106     jack      mobile  28000.0  nashik
6          107    simon      laptop      NaN    pune
7          108    peter      mobile  25000.0  mumbai
8          109    priya      laptop  65000.0  nagpur
9          110    rahul      mobile      NaN  mumbai

In [16]:
df.drop_duplicates(subset='customer',inplace=True)
df

   customer id customer     product    price    city
0          101    rahul      laptop  55000.0    pune
1          102    james      mobile  25000.0    pune
2          103     john      laptop  60000.0    pune
3          104    priya  headphones      NaN  mumbai
4          105      ken      laptop  55000.0    pune
5          106     jack      mobile  28000.0  nashik
6          107    simon      laptop      NaN    pune
7          108    peter      mobile  25000.0  mumbai

In [17]:
df["price"]=df["price"].fillna(df.groupby("product")["price"].transform("mean"))
df

   customer id customer     product         price    city
0          101    rahul      laptop  55000.000000    pune
1          102    james      mobile  25000.000000    pune
2          103     john      laptop  60000.000000    pune
3          104    priya  headphones           NaN  mumbai
4          105      ken      laptop  55000.000000    pune
5          106     jack      mobile  28000.000000  nashik
6          107    simon      laptop  56666.666667    pune
7          108    peter      mobile  25000.000000  mumbai

In [19]:
df=df[df["price"].isnull()==False]
df

   customer id customer product         price    city
0          101    rahul  laptop  55000.000000    pune
1          102    james  mobile  25000.000000    pune
2          103     john  laptop  60000.000000    pune
4          105      ken  laptop  55000.000000    pune
5          106     jack  mobile  28000.000000  nashik
6          107    simon  laptop  56666.666667    pune
7          108    peter  mobile  25000.000000  mumbai

In [20]:
#Business Insights
print("Average Price:", round(df["price"].mean(),2))
print("Total Revenue:", round(df["price"].sum(),2))
print("Products Sold:\n",df["product"].value_counts())

Average Price: 43523.81
Total Revenue: 304666.67
Products Sold:
 product
laptop    4
mobile    3
Name: count, dtype: int64

In [21]:
laptop_customers=df[df["product"]=="laptop"]
laptop_customers

   customer id customer product         price  city
0          101    rahul  laptop  55000.000000  pune
2          103     john  laptop  60000.000000  pune
4          105      ken  laptop  55000.000000  pune
6          107    simon  laptop  56666.666667  pune