1. Which product is purchased most frequently?
2. How many laptops were sold 
3. Which category has the highest number of products?

Customer analysis:

4. Find number of male and female customers?
5. Find average customer age? 
6. Find youngest customer?

Sales analysis: 

7. Calculate Total sale Find total sale, average sales, highest sale

City wise analysis: 

8. Which city has highest number of customers?
9. Which city generated the highest sale? Use group by.

In [125]:
import pandas as pd

In [126]:
df=pd.read_csv("skills1b.csv")
df

,order id,customer,gender,age,city,product,price,category,quantity
0,101,rahul,M,28,pune,laptop,55000.0,Electronics,1
1,102,james,M,32,pune,mobile,25000.0,Electronics,2
2,103,john,M,25,pune,laptop,60000.0,Electronics,1
3,104,priya,F,27,mumbai,headphones,NaN,Accessories,1
4,105,ken,M,35,pune,laptop,55000.0,Electronics,1
5,106,natasha,F,29,nashik,mobile,28000.0,Electronics,2
6,107,simon,M,31,pune,laptop,NaN,Electronics,1
7,108,peter,M,26,mumbai,mobile,25000.0,Electronics,3
8,109,priya,F,27,nagpur,laptop,65000.0,Electronics,1
9,110,rahul,M,28,mumbai,mobile,NaN,Electronics,2

In [127]:
df.drop_duplicates()
df

,order id,customer,gender,age,city,product,price,category,quantity
0,101,rahul,M,28,pune,laptop,55000.0,Electronics,1
1,102,james,M,32,pune,mobile,25000.0,Electronics,2
2,103,john,M,25,pune,laptop,60000.0,Electronics,1
3,104,priya,F,27,mumbai,headphones,NaN,Accessories,1
4,105,ken,M,35,pune,laptop,55000.0,Electronics,1
5,106,natasha,F,29,nashik,mobile,28000.0,Electronics,2
6,107,simon,M,31,pune,laptop,NaN,Electronics,1
7,108,peter,M,26,mumbai,mobile,25000.0,Electronics,3
8,109,priya,F,27,nagpur,laptop,65000.0,Electronics,1
9,110,rahul,M,28,mumbai,mobile,NaN,Electronics,2

In [128]:
df['price']=df['price'].fillna(df.groupby('product')['price'].transform('mean'))
df

,order id,customer,gender,age,city,product,price,category,quantity
0,101,rahul,M,28,pune,laptop,55000.0,Electronics,1
1,102,james,M,32,pune,mobile,25000.0,Electronics,2
2,103,john,M,25,pune,laptop,60000.0,Electronics,1
3,104,priya,F,27,mumbai,headphones,NaN,Accessories,1
4,105,ken,M,35,pune,laptop,55000.0,Electronics,1
5,106,natasha,F,29,nashik,mobile,28000.0,Electronics,2
6,107,simon,M,31,pune,laptop,58750.0,Electronics,1
7,108,peter,M,26,mumbai,mobile,25000.0,Electronics,3
8,109,priya,F,27,nagpur,laptop,65000.0,Electronics,1
9,110,rahul,M,28,mumbai,mobile,26000.0,Electronics,2

In [129]:
df=df[df["price"].isnull()==False]
df

,order id,customer,gender,age,city,product,price,category,quantity
0,101,rahul,M,28,pune,laptop,55000.0,Electronics,1
1,102,james,M,32,pune,mobile,25000.0,Electronics,2
2,103,john,M,25,pune,laptop,60000.0,Electronics,1
4,105,ken,M,35,pune,laptop,55000.0,Electronics,1
5,106,natasha,F,29,nashik,mobile,28000.0,Electronics,2
6,107,simon,M,31,pune,laptop,58750.0,Electronics,1
7,108,peter,M,26,mumbai,mobile,25000.0,Electronics,3
8,109,priya,F,27,nagpur,laptop,65000.0,Electronics,1
9,110,rahul,M,28,mumbai,mobile,26000.0,Electronics,2

In [130]:
#q1. Which product is purchased most frequently?
df.groupby('product')['quantity'].sum().idxmax()

'mobile'

In [131]:
#q2. How many laptops were sold?
int(df[df['product']=='laptop']['quantity'].sum())

5

In [132]:
#q3.Which category has the highest number of products?
col=df.groupby('category')['product'].count().idxmax()
val=df.groupby('category')['product'].count().max()

print(col,val)

Electronics 9

In [133]:
#4. Find number of male and female customers?
df['gender'].value_counts()

gender
M    7
F    2
Name: count, dtype: int64

In [134]:
#5. Find average customer age? 
float(df['age'].mean())

29.0

In [135]:
#6. Find youngest customer?
float(df['age'].min())

25.0

In [136]:
#7. Calculate Total sale, average sales, highest sale
total=df['price'].sum()
avg=df['price'].mean()
highest=df['price'].max()
print("total sales:",total,"\naverage sales:",round(avg,2),"\nhighest sale:",highest)

total sales: 397750.0
average sales: 44194.44
highest sale: 65000.0

In [137]:
#8. Which city has highest number of customers?
df['city'].value_counts().idxmax()

'pune'

In [138]:
#9. Which city generated the highest sale?
col=df.groupby('city')['price'].max().idxmax()
val=df['price'].max()

print(col,val)

nagpur 65000.0