In [1]:
#to remove element from list
l=[10,20,30,40]
l.remove(10)
print(l,type(l))

[20, 30, 40] <class 'list'>

In [2]:
#convert list into tuple and display results
t=tuple(l)
print(t,type(t))

(20, 30, 40) <class 'tuple'>

In [3]:
#merge 2 dictionaries into 1
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3, "d": 4}
dict3 = dict1 | dict2

print("Merged Dictionary:", dict3)

Merged Dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [4]:
#count the occurence of an element in a tuple
t=(10,20,30,20,10)
print(t.count(10))

2

In [5]:
#to use a numpy array
import numpy as np
n=np.array([10,20,30,40])
print(n)

[10 20 30 40]

In [6]:
#handling missing values
mean=np.nanmean(n)
print(mean)

25.0

In [7]:
#data reshaping
#convert 1d into 2d array
n.reshape(2,2)

array([[10, 20],
       [30, 40]])

In [8]:
sample=np.random.randint(1,100,10)
print(sample)

[85 94  6 10 31 73 26 81 21 38]

In [9]:
data1=np.arange(20)

train,test=np.split(data1,[15])
print("train:",train)
print("test:",test)

train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
test: [15 16 17 18 19]

In [41]:
#pandas
import pandas as pd
marks=pd.Series([10,20,30,40])
marks

0    10
1    20
2    30
3    40
dtype: int64

In [42]:
df=pd.DataFrame({
    "Name":['josh','john','alice'],
    "Age":[22,23,24],
    "Marks":[90,80,70]
})

df

    Name  Age  Marks
0   josh   22     90
1   john   23     80
2  alice   24     70

In [43]:
df1=pd.DataFrame({
    "Name":['josh','john','alice'],
    "Age":[22,23,np.nan],
    "Marks":[90,np.nan,70]
})

print(df1.isnull(),"\n")
print(df1.isnull().sum())

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False

Name     0
Age      1
Marks    1
dtype: int64

In [44]:
df1["Marks"].fillna(df["Marks"].mean(),inplace=True)
df1

C:\Users\joshb\AppData\Local\Temp\ipykernel_8604\345987055.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Marks"].fillna(df["Marks"].mean(),inplace=True)

    Name   Age  Marks
0   josh  22.0   90.0
1   john  23.0   80.0
2  alice   NaN   70.0

In [45]:
df1.dropna(inplace=True)
df1

   Name   Age  Marks
0  josh  22.0   90.0
1  john  23.0   80.0

In [46]:
df1.drop_duplicates(inplace=True)
df1

   Name   Age  Marks
0  josh  22.0   90.0
1  john  23.0   80.0

In [47]:
df1.rename(columns={"Marks":"Score"}, inplace=True)
df1

   Name   Age  Score
0  josh  22.0   90.0
1  john  23.0   80.0

In [48]:
df2=pd.read_csv(r'data/P6-UK-Bank-Customers.csv')
df2.head()

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
0,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
4,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79